version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    container_name: databaseWholesaler
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4307:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  databaseTest:
    container_name: databaseWholesalerTest
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker_test
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_TCP_PORT: 3307
    ports:
      - '4308:3307'
    volumes:
      - ./mysql_test:/var/lib/mysql
volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###